sudo: false
language: python
matrix:
    include:
        - python: 2.6
          dist: trusty

        - python: 2.7
          dist: trusty
        - python: 2.7
          dist: xenial
        - python: 2.7
          dist: bionic

        - python: 3.5
          dist: xenial
        - python: 3.5
          dist: bionic

        - python: 3.6
          dist: xenial
        - python: 3.6
          dist: bionic

        - python: 3.7
          dist: xenial
        - python: 3.7
          dist: bionic

        - python: 3.8
          dist: xenial
        - python: 3.8
          dist: bionic

script:
  - export DELAY=1 
  - export NUM_LINES=5 
  - export SLEEP_TIME=$((DELAY*NUM_LINES))
  - python ./dstat --version
  - python ./dstat -taf $DELAY $NUM_LINES
  - python ./dstat --helloworld $DELAY $NUM_LINES
  #- python ./dstat -t --all-plugins $DELAY $NUM_LINES
  # Test CSV output for 3 lines of 1 second intervals while running in background
  - python ./dstat -cdmnpt --output dstat.csv $DELAY $NUM_LINES &
  # Assert CSV file is not empty
  - sleep $SLEEP_TIME && if [[ ! -s dstat.csv ]]; then exit 1; else cat dstat.csv; fi
